title: stex.codes
tagline: Ruby and Raccoons
description: >-
  Blog about personal (and sometimes work) projects and experiences, Ruby and sometimes Raccoons.
baseurl: ""
url: "https://stex.codes"
logo: "logo-raccoon.jpg"
timezone: Europe/Berlin

owner:
  name: "Stefan Exner"
  email: stex@hey.com
  twitter: Tagolus
  github:  stex

twitter:
  username: Tagolus
  card: summary

social:
  name: Stefan Exner
  links:
    - https://twitter.com/Tagolus
    - https://www.xing.com/profile/Stefan_Exner13
    - https://github.com/stex

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/logo-raccoon.jpg
      author:
        name: "Stefan Exner"
        twitter: Tagolus

permalink: /:year/:month/:day/:title:output_ext

# Build settings
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-sitemap
  - custom_ruby

pagination:
  enabled: true
  collection: "posts"
  per_page: 10
  sort_reverse: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .idea
  - .gitignore
  - bin/
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Dockerfile
  - Dockerfile.dev
  - docker-compose.yml
  - package.json
  - nginx.conf
  - node_modules/
  - thumbor-dev
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
